"""
api.py
------
Flask REST API serving the Index Advisor dashboard.
"""

import json
import sqlite3
import sys
from pathlib import Path
from flask import Flask, jsonify, render_template_string, send_from_directory


sys.path.insert(0, str(Path(__file__).parent))

from index_advisor_model import generate_recommendations, train_models, build_features
from query_ingester import simulate_query_logs

import pandas as pd

app = Flask(__name__)
DB_PATH = "logs/query_logs.db"


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


@app.route("/api/recommendations")
def recommendations():
    try:
        recs = generate_recommendations(DB_PATH)
        return jsonify({"status": "ok", "data": recs})
    except FileNotFoundError as e:
        return jsonify({"status": "error", "message": str(e)}), 404


@app.route("/api/stats")
def stats():
    conn = get_db()
    
    total_queries = conn.execute("SELECT COUNT(*) as c FROM query_logs").fetchone()["c"]
    total_columns = conn.execute("SELECT COUNT(*) as c FROM column_stats").fetchone()["c"]
    
    slowest = conn.execute("""
        SELECT table_name, column_name, avg_exec_time_ms, total_queries, seq_scan_pct
        FROM column_stats
        ORDER BY avg_exec_time_ms DESC LIMIT 10
    """).fetchall()
    
    busiest = conn.execute("""
        SELECT table_name, column_name, total_queries, avg_exec_time_ms
        FROM column_stats
        ORDER BY total_queries DESC LIMIT 10
    """).fetchall()
    
    time_series = conn.execute("""
        SELECT 
            strftime('%Y-%m-%d %H:00', recorded_at) as hour,
            AVG(execution_time_ms) as avg_time,
            COUNT(*) as query_count
        FROM query_logs
        GROUP BY hour
        ORDER BY hour
        LIMIT 168
    """).fetchall()
    
    conn.close()
    
    return jsonify({
        "status": "ok",
        "total_queries": total_queries,
        "total_columns_analyzed": total_columns,
        "slowest_columns": [dict(r) for r in slowest],
        "busiest_columns": [dict(r) for r in busiest],
        "time_series": [dict(r) for r in time_series]
    })


@app.route("/api/reingest")
def reingest():
    simulate_query_logs(3000, DB_PATH)
    train_models(DB_PATH)
    return jsonify({"status": "ok", "message": "Re-ingested logs and retrained model."})


@app.route("/api/generate-script")
def generate_script():
    recs = generate_recommendations(DB_PATH)
    lines = [
        "-- ============================================================",
        "-- AUTO-GENERATED INDEX RECOMMENDATIONS",
        "-- Generated by ML-Powered Database Index Advisor",
        "-- WARNING: Review before running in production!",
        "-- Use CONCURRENTLY to avoid locking tables in production.",
        "-- ============================================================",
        "",
        "BEGIN;"
    ]
    
    recommended = [r for r in recs if r["should_index"]]
    for r in recommended:
        lines.append(f"\n-- {r['table']}.{r['column']}: ~{r['estimated_improvement_pct']:.0f}% improvement expected")
        lines.append(f"-- Confidence: {r['confidence']:.1%} | Queries/period: {r['query_frequency']}")
        lines.append(r["sql"])
    
    lines += ["", "COMMIT;"]
    return jsonify({"status": "ok", "script": "\n".join(lines), "count": len(recommended)})


if __name__ == "__main__":
    # Bootstrap if needed
    if not Path(DB_PATH).exists():
        print("[+] No database found. Generating synthetic logs...")
        simulate_query_logs(3000, DB_PATH)
    
    if not Path("models/index_classifier.pkl").exists():
        print("[+] No model found. Training...")
        train_models(DB_PATH)
    
    app.run(debug=False, port=5050)
