-- ============================================================
-- AUTO-GENERATED INDEX RECOMMENDATIONS
-- Generated by ML-Powered Database Index Advisor
-- Review carefully before running in production!
-- ============================================================

BEGIN;

-- orders.created_at: ~85% improvement | confidence 100%
CREATE INDEX idx_orders_created_at ON orders USING BRIN (created_at);
-- payments.amount: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_payments_amount ON payments (amount);
-- products.price: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_products_price ON products (price);
-- logs.user_id: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_logs_user_id ON logs (user_id);
-- logs.created_at: ~85% improvement | confidence 100%
CREATE INDEX idx_logs_created_at ON logs USING BRIN (created_at);
-- products.category_id: ~85% improvement | confidence 100%
CREATE INDEX idx_products_category_id ON products USING BRIN (category_id);
-- reviews.product_id: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_reviews_product_id ON reviews (product_id);
-- sessions.user_id: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_sessions_user_id ON sessions (user_id);
-- users.email: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_users_email ON users (email);
-- payments.order_id: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_payments_order_id ON payments (order_id);
-- inventory.product_id: ~85% improvement | confidence 100%
CREATE INDEX CONCURRENTLY idx_inventory_product_id ON inventory (product_id);

COMMIT;